name: Publish App Release

on:
  push:
    tags:
      - 'App-v*'
    branches-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and run unit tests
        run: ./gradlew clean testDebug

  publish:
    name: Build and Publish Release APK
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number + 1000000}}
          versionName: ${{ github.ref_name | sed 's/^App-v\([0-9.]*\).*/\1/' }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew clean :app:bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_AUTH_JSON }}
          packageName: 'hu.bbara.breakthesnooze'
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: 'internal'
          status: 'completed'